# Generated by Django 6.1.2 on 2026-10-08 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата начала')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата окончания')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='catalog.bike', verbose_name='Велосипед')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='rentals.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rentals', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
                'ordering': ('-start_datetime',),
                'indexes': [models.Index(fields=['client'], name='rentals_ren_client__7a7b6c_idx'), models.Index(fields=['bike'], name='rentals_ren_bike_id_2f5896_idx'), models.Index(fields=['start_datetime'], name='rentals_ren_start_d_ddaffd_idx'), models.Index(fields=['end_datetime'], name='rentals_ren_end_dat_2f6285_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='rental_dates_valid'), models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='rental_cost_non_negative'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'completed', 'canceled'])), name='rental_status_valid')],
            },
        ),
    ]
