# Generated by Django 6.1.2 on 2026-10-08 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rental',
            name='rental_status_valid',
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'completed', 'cancelled'])), name='rental_status_valid'),
        ),
    ]
