# Generated by Django 6.1.2 on 2026-10-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('base_price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена за сутки')),
            ],
            options={
                'verbose_name': 'Тип велосипеда',
                'verbose_name_plural': 'Типы велосипедов',
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('base_price_per_day__gt', 0)), name='bike_type_price_positive')],
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Серийный номер')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('rented', 'В прокате'), ('maintenance', 'Обслуживание')], default='available', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('bike_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bikes', to='catalog.biketype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеды',
                'ordering': ('model',),
                'indexes': [models.Index(fields=['status'], name='catalog_bik_status_edbed7_idx'), models.Index(fields=['bike_type'], name='catalog_bik_bike_ty_6a9179_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['available', 'rented', 'maintenance'])), name='bike_status_available')],
            },
        ),
    ]
